[build]
target = "bare_metal_x86_64_target.json"
rustflags = [
    "-C", "link-arg=--script=linker_script.ld"
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
