emit_mode = "Files"
make_backup = false
unstable_features = true
max_width = 110
comment_width = 110
wrap_comments = true
normalize_doc_attributes = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
control_brace_style = "ClosingNextLine"
trailing_comma = "Never"
blank_lines_upper_bound = 3
edition = "2021"
version = "Two"
use_try_shorthand = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
required_version = "1.7.0"
error_on_line_overflow = true
error_on_unformatted = true
single_line_if_else_max_width = 70
single_line_let_else_max_width = 70
combine_control_expr = false
match_block_trailing_comma = true
