[build]
target = "bare_metal_x86_64_target.json"
rustflags = [
    "-C", "link-arg=--verbose", 
    "-C", "link-arg=--script=linker_script.ld",
    "--print", "link-args"
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
